---
# Source: zeebe-cluster/templates/gateway-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "zell-state-runtime-sep-path-zeebe-gateway"
  labels:
    app.kubernetes.io/name: zeebe-cluster
    app.kubernetes.io/instance: zell-state-runtime-sep-path
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: gateway
  annotations:
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zeebe-cluster
      app.kubernetes.io/instance: zell-state-runtime-sep-path
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/component: gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zeebe-cluster
        app.kubernetes.io/instance: zell-state-runtime-sep-path
        app.kubernetes.io/managed-by: Helm
        app.kubernetes.io/component: gateway
      annotations:
    spec:
      containers:
        - name: zeebe-cluster
          image: "gcr.io/zeebe-io/zeebe:zell-state-runtime-sep-path"
          imagePullPolicy: Always
          ports:
            - containerPort: 9600
              name: http
            - containerPort: 26500
              name: gateway
            - containerPort: 26502
              name: internal
          env:
            - name: ZEEBE_STANDALONE_GATEWAY
              value: "true"
            - name: ZEEBE_GATEWAY_CLUSTER_CLUSTERNAME
              value: zell-state-runtime-sep-path-zeebe
            - name: ZEEBE_GATEWAY_CLUSTER_MEMBERID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: ZEEBE_LOG_LEVEL
              value: "debug"
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:MaxRAMPercentage=25.0 -XX:+ExitOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/usr/local/zeebe/data -XX:ErrorFile=/usr/local/zeebe/data/zeebe_error%p.log -Xlog:gc*:file=/usr/local/zeebe/data/gc.log:time:filecount=7,filesize=8M"
            - name: ZEEBE_GATEWAY_CLUSTER_CONTACTPOINT
              value: zell-state-runtime-sep-path-zeebe:26502
            - name: ZEEBE_GATEWAY_NETWORK_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_NETWORK_PORT
              value: "26500"
            - name: ZEEBE_GATEWAY_CLUSTER_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: ZEEBE_GATEWAY_CLUSTER_PORT
              value: "26502"
            - name: ZEEBE_GATEWAY_MONITORING_HOST
              value: 0.0.0.0
            - name: ZEEBE_GATEWAY_MONITORING_PORT
              value: "9600"
            - name: ZEEBE_LOG_APPENDER
              value: Stackdriver
            - name: ZEEBE_LOG_STACKDRIVER_SERVICENAME
              value: zeebe-gateway
            - name: ZEEBE_LOG_STACKDRIVER_SERVICEVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: ATOMIX_LOG_LEVEL
              value: INFO
            - name: ZEEBE_GATEWAY_MONITORING_ENABLED
              value: "true"
            - name: ZEEBE_GATEWAY_THREADS_MANAGEMENTTHREADS
              value: "4"
          volumeMounts:
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
          readinessProbe:
            tcpSocket:
              port: gateway
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 2
              memory: 1Gi
      volumes:
        - name: config
          configMap:
            name: zell-state-runtime-sep-path-zeebe-cluster
            defaultMode: 0744
