---
# Source: zeebe-cluster/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "zell-state-runtime-sep-path-zeebe"
  labels:
    app.kubernetes.io/name: zeebe-cluster
    app.kubernetes.io/instance: zell-state-runtime-sep-path
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: broker
    app: zeebe
  annotations:
    null    
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  type: ClusterIP
  ports:
    - port: 9600
      protocol: TCP
      name: http  
    - port: 26502
      protocol: TCP
      name: internal
    - port: 26501
      protocol: TCP
      name: command
  selector:
    app.kubernetes.io/name: zeebe-cluster
    app.kubernetes.io/instance: zell-state-runtime-sep-path
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/component: broker
